name: deranest
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  permission_handler: ^12.0.1
  auto_size_text: ^3.0.0  
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  extensions_kit: ^1.1.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.1
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1  
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  contacts_service_plus: ^0.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.1.0
  path: ^1.9.0
  emoji_picker_flutter: ^4.3.0  
  circle_bottom_navigation: ^2.0.0
  step_progress_indicator: ^1.0.2
  story_view: ^0.16.5
  vector_graphics: ^1.1.19
  voice_note_kit: ^1.2.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.17
flutter:
  uses-material-design: true
  # Assets:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/audio/
    
    - path: assets/svg/
      transformers:
        - package: vector_graphics_compiler
  # FONTS
  fonts:
    - family: Poppins_Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
