// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYyjvWAg-NJSwIqK0xGuTd5V2OIC3Fe0',
    appId: '1:278700757526:web:7ba4d9cdea66cbcb0d9b37',
    messagingSenderId: '278700757526',
    projectId: 'deranest-f120e',
    authDomain: 'deranest-f120e.firebaseapp.com',
    storageBucket: 'deranest-f120e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0EyNKMZ_-4kjBLhX6ilLFeEUbJjjwWc',
    appId: '1:278700757526:android:a5048159645a8d520d9b37',
    messagingSenderId: '278700757526',
    projectId: 'deranest-f120e',
    storageBucket: 'deranest-f120e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN5IYLhBTWHk4X1iKrf-_8-XkUYlv0pxw',
    appId: '1:278700757526:ios:9d1066707a469c420d9b37',
    messagingSenderId: '278700757526',
    projectId: 'deranest-f120e',
    storageBucket: 'deranest-f120e.firebasestorage.app',
    iosBundleId: 'com.example.deranest',
  );
}
